#!/usr/bin/env python3
"""
Dashboard data refresh script.
Fetches GitHub PRs, Jira tickets, Claude filesystem data, Google Calendar events,
PagerDuty on-call, and app health checks.
Writes separate cache files then merges into dashboard-data.js.

Usage:
  python3 refresh.py             # full refresh (all sources)
  python3 refresh.py --github    # GitHub PRs only
  python3 refresh.py --jira      # Jira tickets only
  python3 refresh.py --local     # Plans + Claude filesystem + Calendar + On-call + Apps
  python3 refresh.py --oncall    # PagerDuty on-call only
  python3 refresh.py --calendar  # Google Calendar only

GitHub rate limits:
  REST core:  5,000 req/hr   — gh api, gh pr list/view
  Search:        30 req/min  — gh search prs / gh api search/issues  ← tightest
  GraphQL:    5,000 req/hr   — gh pr list --json (enriched fields)
  Secondary:  undocumented burst detection — avoid >1 req/s sustained

Search strategy (minimises Search API calls):
  - fetch_all_open_prs:   2 searches (team open + assigned open, merged client-side)
  - fetch_all_merged_prs: 1 search   (mine + team, last 7 days)
  Total: 3 Search calls per full run.

  NOTE: `gh search prs` mangles raw author: qualifiers in positional args, treating
  them as text rather than GitHub search qualifiers and wrapping them in quotes.
  Use `gh api search/issues?q=...` directly to pass arbitrary query strings.
"""
import argparse
import json
import os
import re
import sys
from datetime import datetime, timezone

from fetchers.utils import (
    DIR, Progress, check_rate_limit,
    MY_USERNAME, ORG, TEAM_MEMBERS, PRIMARY_REPOS, MY_REPOS,
    PD_SCHEDULE_IDS, JIRA_PROJECT, GCAL_CREDS_DIR,
    DASH_TITLE, DASH_SUBTITLE, ALL_TEAM,
    JIRA_BASE_URL, PD_BASE_URL, SLACK_BASE_URL, TEAM_CONFIG, CONFIG_REPOS,
    DEPLOY_FAVICON_DOMAIN,
)
from fetchers.github import (
    fetch_required_approvals, fetch_staging_merged,
    fetch_all_open_prs, fetch_all_merged_prs, enrich_all_prs,
    fetch_my_branches, fetch_repo_prs, is_repo_archived, _pr_repo_name,
)
from fetchers.jira     import fetch_jira_tickets
from fetchers.local    import fetch_claude_data, fetch_plans, parse_next_actions, parse_internal_priorities
from fetchers.oncall   import fetch_oncall_data
from fetchers.calendar import fetch_calendar_events
from fetchers.apps     import fetch_apps_data

OUTPUT       = os.path.join(DIR, "dashboard-data.js")
CACHE_GITHUB = os.path.join(DIR, "cache-github.js")
CACHE_JIRA   = os.path.join(DIR, "cache-jira.js")
CACHE_LOCAL  = os.path.join(DIR, "cache-local.js")


def _load_cache(path):
    if not os.path.isfile(path):
        return {}
    try:
        with open(path) as f:
            content = f.read()
        m = re.search(r'window\.\w+ = ({.*});\s*$', content, re.DOTALL)
        if m:
            return json.loads(m.group(1))
    except Exception:
        pass
    return {}


def _write_cache(path, var_name, data):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(f"// Generated by refresh.py at {data['generatedAt']}\n")
        f.write(f"window.{var_name} = {json.dumps(data, indent=2)};\n")


def _write_merged():
    github = _load_cache(CACHE_GITHUB)
    jira   = _load_cache(CACHE_JIRA)
    local  = _load_cache(CACHE_LOCAL)

    refreshed_at = {}
    for key, cache in [("github", github), ("jira", jira), ("local", local)]:
        ts = cache.get("generatedAt")
        if ts:
            refreshed_at[key] = ts
    for key in ("oncall", "calendar"):
        ts = local.get(f"{key}RefreshedAt")
        if ts:
            refreshed_at[key] = ts

    source_times = list(refreshed_at.values())
    generated_at = min(source_times) if source_times else datetime.now(timezone.utc).isoformat()

    merged = {**github, **jira, **local,
              "generatedAt": generated_at,
              "refreshedAt": refreshed_at}
    os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)
    with open(OUTPUT, "w") as f:
        f.write("// Generated by refresh.py — merged from caches\n")
        f.write(f"// Do not edit manually — regenerate: python3 {os.path.basename(__file__)}\n")
        f.write(f"window.DASHBOARD_DATA = {json.dumps(merged, indent=2)};\n")


def main():
    parser = argparse.ArgumentParser(description="Refresh dashboard data caches.")
    parser.add_argument("--github",   action="store_true", help="GitHub PRs only")
    parser.add_argument("--jira",     action="store_true", help="Jira tickets only")
    parser.add_argument("--local",    action="store_true", help="Plans + Claude filesystem + Calendar + On-call + Apps")
    parser.add_argument("--oncall",   action="store_true", help="PagerDuty on-call only")
    parser.add_argument("--calendar", action="store_true", help="Google Calendar only")
    args    = parser.parse_args()
    run_all = not any([args.github, args.jira, args.local, args.oncall, args.calendar])

    do_github   = run_all or args.github
    do_jira     = run_all or args.jira
    do_local    = run_all or args.local
    do_oncall   = run_all or args.local or args.oncall
    do_calendar = run_all or args.local or args.calendar

    github_fixed = (
        1                    # check_rate_limit
        + len(PRIMARY_REPOS) # fetch_required_approvals
        + len(MY_REPOS)      # fetch_staging_merged
        + 2                  # fetch_all_open_prs  (team + assigned)
        + 1                  # fetch_all_merged_prs
        + len(PRIMARY_REPOS) # fetch_my_branches
        + len(PRIMARY_REPOS) # fetch_repo_prs
    )
    total = 0
    if do_github:   total += github_fixed
    if do_jira:     total += 1
    if do_local:    total += 2  # claude_data + plans
    if do_oncall and PD_SCHEDULE_IDS: total += 1
    if do_calendar: total += 1

    progress = Progress(total=total)

    if do_github:
        print("Refreshing GitHub PR data...", file=sys.stderr)

        check_rate_limit(progress)
        progress.step("Checked rate limits")

        required_approvals = fetch_required_approvals(progress)
        staging_merged     = fetch_staging_merged(progress)

        all_open = fetch_all_open_prs(progress)
        my_prs_raw   = [p for p in all_open if (p.get("author") or {}).get("login") == MY_USERNAME]
        team_prs_raw = [p for p in all_open if (p.get("author") or {}).get("login") in TEAM_MEMBERS]
        assigned_raw = [p for p in all_open if (p.get("author") or {}).get("login") not in ALL_TEAM]

        all_merged    = fetch_all_merged_prs(progress)
        my_merged_prs = [p for p in all_merged if (p.get("author") or {}).get("login") == MY_USERNAME]
        for p in my_merged_prs:
            p["isMerged"] = True
            p["repoName"] = (p.get("repository") or {}).get("name", "")

        all_open_prs = my_prs_raw + team_prs_raw + assigned_raw
        enriched     = enrich_all_prs(all_open_prs, required_approvals, staging_merged, progress)

        my_prs       = [p for p in enriched if (p.get("author") or {}).get("login") == MY_USERNAME]
        team_prs     = [p for p in enriched if (p.get("author") or {}).get("login") in TEAM_MEMBERS
                        and not is_repo_archived(_pr_repo_name(p), progress)]
        assigned_prs = [p for p in enriched if (p.get("author") or {}).get("login") not in ALL_TEAM
                        and not is_repo_archived(_pr_repo_name(p), progress)]

        open_head_refs: dict[str, set] = {}
        for pr in enriched:
            repo = _pr_repo_name(pr)
            head = pr.get("headRefName", "")
            if repo and head:
                open_head_refs.setdefault(repo, set()).add(head)

        my_branches = fetch_my_branches(open_head_refs, progress)
        repo_prs    = fetch_repo_prs(progress)

        github_data = {
            "generatedAt": datetime.now(timezone.utc).isoformat(),
            "myPRs":         my_prs,
            "myMergedPRs":   my_merged_prs,
            "teamPRs":       team_prs,
            "repoPRs":       repo_prs,
            "assignedPRs":   assigned_prs,
            "myBranches":    my_branches,
        }
        _write_cache(CACHE_GITHUB, "DASHBOARD_GITHUB", github_data)

        progress.message(f"  My PRs: {len(my_prs)}")
        progress.message(f"  Team PRs: {len(team_prs)}")
        progress.message(f"  Repo PRs (non-team): {len(repo_prs)}")
        progress.message(f"  Assigned to me: {len(assigned_prs)}")
        progress.message(f"  My branches: {len(my_branches)}")

    if do_jira:
        print("Refreshing Jira data...", file=sys.stderr)
        jira_tickets = fetch_jira_tickets(progress)
        jira_data = {
            "generatedAt": datetime.now(timezone.utc).isoformat(),
            "jiraTickets": jira_tickets,
        }
        progress.message(f"  Jira tickets: {len(jira_tickets)}")
        _write_cache(CACHE_JIRA, "DASHBOARD_JIRA", jira_data)

    if do_local or do_oncall or do_calendar:
        existing = _load_cache(CACHE_LOCAL) if not do_local else {}

        if do_local:
            print("Refreshing local + app health data...", file=sys.stderr)
            claude_data         = fetch_claude_data(progress)
            plans               = fetch_plans(progress)
            next_actions        = parse_next_actions()
            internal_priorities = parse_internal_priorities()
            apps_result         = fetch_apps_data(progress)
            app_data            = apps_result.get("appData", {})
            apps_refreshed_at   = apps_result.get("appsRefreshedAt", "")
        else:
            claude_data         = existing.get("claudeData", {})
            plans               = existing.get("plans", [])
            next_actions        = existing.get("nextActions", {})
            internal_priorities = existing.get("internalPriorities", {})
            app_data            = existing.get("appData", {})
            apps_refreshed_at   = existing.get("appsRefreshedAt", "")

        if do_oncall:
            if args.oncall and not do_local:
                print("Refreshing PagerDuty on-call...", file=sys.stderr)
            oncall_data         = fetch_oncall_data(progress)
            oncall_refreshed_at = datetime.now(timezone.utc).isoformat()
        else:
            oncall_data         = existing.get("oncallData", [])
            oncall_refreshed_at = existing.get("oncallRefreshedAt", "")

        if do_calendar:
            if args.calendar and not do_local:
                print("Refreshing Google Calendar...", file=sys.stderr)
            calendar_events       = fetch_calendar_events(progress)
            calendar_refreshed_at = datetime.now(timezone.utc).isoformat()
        else:
            calendar_events       = existing.get("calendarEvents", [])
            calendar_refreshed_at = existing.get("calendarRefreshedAt", "")

        local_data = {
            "generatedAt":         existing.get("generatedAt", datetime.now(timezone.utc).isoformat()) if not do_local else datetime.now(timezone.utc).isoformat(),
            "oncallRefreshedAt":   oncall_refreshed_at,
            "calendarRefreshedAt": calendar_refreshed_at,
            "appsRefreshedAt":     apps_refreshed_at,
            "githubUsername":      MY_USERNAME,
            "githubOrg":           ORG,
            "primaryRepos":        PRIMARY_REPOS,
            "dashboardTitle":      DASH_TITLE,
            "dashboardSubtitle":   DASH_SUBTITLE,
            "teamMembers":         TEAM_CONFIG,
            "slackBaseUrl":        SLACK_BASE_URL,
            "pdBaseUrl":           PD_BASE_URL,
            "jiraBaseUrl":         JIRA_BASE_URL,
            "configRepos":         CONFIG_REPOS,
            "deployFaviconDomain": DEPLOY_FAVICON_DOMAIN,
            "claudeData":          claude_data,
            "plans":               plans,
            "oncallData":          oncall_data,
            "calendarEvents":      calendar_events,
            "nextActions":         next_actions,
            "internalPriorities":  internal_priorities,
            "appData":             app_data,
        }

        if do_local:
            cd = claude_data
            progress.message(f"  Plans: {len(plans)}")
            if oncall_data:
                progress.message(f"  On-call entries: {len(oncall_data)}")
            if calendar_events:
                progress.message(f"  Calendar events: {len(calendar_events)}")
            progress.message(f"  Skills: {len(cd.get('skills', []))}  Agents: {len(cd.get('agents', []))}  MCP servers: {len(cd.get('mcpServers', []))}")
            if app_data:
                progress.message(f"  Apps: {len(app_data)}")
        elif args.oncall and oncall_data:
            progress.message(f"  On-call entries: {len(oncall_data)}")
        elif args.calendar and calendar_events:
            progress.message(f"  Calendar events: {len(calendar_events)}")

        _write_cache(CACHE_LOCAL, "DASHBOARD_LOCAL", local_data)

    progress.finish()
    print("Merging caches...", file=sys.stderr)
    _write_merged()
    print(f"\nDone — written to {OUTPUT}")
    print("Reload the dashboard in your browser to see updated data.")


if __name__ == "__main__":
    main()
